//HintName: ServiceExtensions.g.cs
// <auto-generated />
#nullable enable

using global::Microsoft.Extensions.DependencyInjection;

using global::Truffleware.Abstractions.Messaging;
using global::Truffleware.CodeAnalysis.Tests.inputs;

namespace Truffleware.Generated;

internal static partial class ServiceCollectionExtensions
{
    public static IServiceCollection AddSenders(this IServiceCollection services)
    {
        services.AddTransient<IRequestSender<Ping, Pong>, SenderPingToPong>();

        return services;
    }

    public static IServiceCollection AddHandlers(this IServiceCollection services)
    {
        // TODO: Warning if there's multiple handlers for the same request-response pair?
        services.AddTransient<IRequestHandler<Ping, Pong>, PingHandler>();

        return services;
    }
}