//HintName: SenderPingToPong_g_cs.cs
// <auto-generated />
#nullable enable

using global::System.Threading.Tasks;

using global::Truffleware.Abstractions.Messaging;
using global::Truffleware.Generated;

using global::Truffleware.CodeAnalysis.Tests.Inputs;

namespace Truffleware.Generated;

public sealed class SenderPingToPong(IRequestHandler<Ping, Pong> handler)
    : IRequestSender<Ping, Pong>
{
    public async Task<Pong> SendAsync(Ping request)
    {
        return await handler.HandleAsync(request);
    }
}