<Project>
    <!-- See https://aka.ms/dotnet/msbuild/customize for more details on customizing your build -->
    <PropertyGroup>
        <!-- General project information -->
        <Authors>Akke Luukkonen</Authors>
        <Copyright>Copyright (c) Akke Luukkonen 2026</Copyright>
        <PackageProjectUrl>https://github.com/Truffleware/truffleware</PackageProjectUrl>
        <PackageTags>truffleware</PackageTags>

        <!-- Packaging -->
        <UseArtifactsOutput>true</UseArtifactsOutput>
        <Version>0.0.1-local</Version>
        <MinVerVersionOverride Condition="'$(CI)' != 'true'">$(Version)</MinVerVersionOverride>
        <PackageReadmeFile>README.md</PackageReadmeFile>
        <PackageLicenseFile>LICENSE</PackageLicenseFile>
        <PackageReleaseNotes>https://github.com/Truffleware/truffleware/blob/master/CHANGELOG.md</PackageReleaseNotes>
        <RepositoryType>git</RepositoryType>
        <RepositoryUrl>https://github.com/Truffleware/truffleware.git</RepositoryUrl>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="MinVer" PrivateAssets="All"/>
        <None Include="$(MSBuildThisFileDirectory)README.md" Pack="true" PackagePath="/"/>
        <None Include="$(MSBuildThisFileDirectory)LICENSE" Pack="true" PackagePath="/"/>
    </ItemGroup>
</Project>
