<Project Sdk="MSTest.Sdk/4.3.3">
    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <LangVersion>latest</LangVersion>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <IsPackable>false</IsPackable>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="../../src/Truffleware.Abstractions/Truffleware.Abstractions.csproj"/>
        <ProjectReference Include="../../src/Truffleware.CodeAnalysis/Truffleware.CodeAnalysis.csproj"/>
        <ProjectReference Include="../../src/Truffleware.CodeAnalysis/Truffleware.CodeAnalysis.csproj"
                          OutputItemType="Analyzer"
                          ReferenceOutputAssembly="false"/>
    </ItemGroup>

    <ItemGroup>
        <!-- Compile removes compilation errors -->
        <Compile Remove="Inputs/RequestResponseGeneratorDuplicateHandlersInput.cs"/>
        <Compile Remove="Inputs/RequestResponseGeneratorNonPartialHandlerInput.cs"/>
        <Compile Remove="Inputs/RequestResponseGeneratorNonPublicHandlerInput.cs"/>
        <!-- None adds them back to the solution view (at least in Rider) -->
        <None Include="Inputs/RequestResponseGeneratorDuplicateHandlersInput.cs"/>
        <None Include="Inputs/RequestResponseGeneratorNonPartialHandlerInput.cs" />
        <None Include="Inputs/RequestResponseGeneratorNonPublicHandlerInput.cs" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="AutoFixture.AutoMoq" />
        <PackageReference Include="Microsoft.Bcl.HashCode"/>
        <PackageReference Include="Microsoft.CodeAnalysis.CSharp"/>
        <PackageReference Include="Microsoft.Extensions.DependencyInjection"/>
        <PackageReference Include="Microsoft.NET.Test.Sdk"/>
        <PackageReference Include="Moq" />
        <PackageReference Include="Verify.MSTest"/>
        <PackageReference Include="Verify.SourceGenerators"/>
    </ItemGroup>
</Project>
