<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <Authors>Akke Luukkonen</Authors>
        <Description>Abstractions used by Truffleware.</Description>

        <TargetFrameworks>netstandard2.0;net10.0</TargetFrameworks>
        <LangVersion>12.0</LangVersion>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>

        <DebugSymbols>true</DebugSymbols>
        <DebugType>portable</DebugType>
        <OutputType>library</OutputType>
    </PropertyGroup>

</Project>
