//HintName: PingHandler.g.cs
// <auto-generated />
#nullable enable

using global::Truffleware.Abstractions.Messaging;
using global::Truffleware.Generated;

namespace Truffleware.CodeAnalysis.Tests.Inputs;

public partial class PingHandler :
    IRequestHandler<Ping, Pong>
{
}