<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <!-- General project information -->
        <Description>Analyzers and generators for Truffleware.</Description>

        <!-- Target frameworks and language settings -->
        <TargetFramework>netstandard2.0</TargetFramework>
        <LangVersion>latest</LangVersion>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>

        <!-- Output type -->
        <OutputType>library</OutputType>

        <!-- Debug settings -->
        <DebugSymbols>true</DebugSymbols>
        <DebugType>portable</DebugType>

        <!-- Analyzer specific rules -->
        <EnforceExtendedAnalyzerRules>true</EnforceExtendedAnalyzerRules>
        <IsRoslynComponent>true</IsRoslynComponent>
        <IncludeBuildOutput>false</IncludeBuildOutput>
        <NoPackageAnalysis>true</NoPackageAnalysis>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.Bcl.HashCode" GeneratePathProperty="true" PrivateAssets="all"/>
        <PackageReference Include="Microsoft.CodeAnalysis.Analyzers" PrivateAssets="all"/>
        <PackageReference Include="Microsoft.CodeAnalysis.CSharp" PrivateAssets="all"/>
    </ItemGroup>

    <PropertyGroup>
        <GetTargetPathDependsOn>$(GetTargetPathDependsOn);GetDependencyTargetPaths</GetTargetPathDependsOn>
    </PropertyGroup>

    <Target Name="GetDependencyTargetPaths">
        <ItemGroup>
            <TargetPathWithTargetPlatformMoniker
                    Include="$(PkgMicrosoft_Bcl_HashCode)\lib\netstandard2.0\Microsoft.Bcl.HashCode.dll"
                    IncludeRuntimeDependency="false"/>

            <None Include="$(PkgMicrosoft_Bcl_HashCode)\lib\netstandard2.0\Microsoft.Bcl.HashCode.dll"
                  Pack="true"
                  PackagePath="analyzers/dotnet/cs"
                  Visible="false"/>
        </ItemGroup>
    </Target>

    <ItemGroup>
        <ProjectReference Include="../Truffleware.Abstractions/Truffleware.Abstractions.csproj"
                          PrivateAssets="all"
                          ReferenceOutputAssembly="true"
                          OutputItemType="AnalyzerDependency"/>
    </ItemGroup>

    <ItemGroup>
        <None Include="$(OutputPath)\$(AssemblyName).dll" Pack="true" PackagePath="analyzers/dotnet/cs" Visible="false"/>
        <None Include="$(OutputPath)\Truffleware.Abstractions.dll" Pack="true" PackagePath="analyzers/dotnet/cs" Visible="false"/>
        <None Include="$(OutputPath)\Truffleware.Abstractions.dll" Pack="true" PackagePath="lib/netstandard2.0" Visible="false"/>
    </ItemGroup>

    <ItemGroup>
        <AdditionalFiles Include="AnalyzerReleases.Shipped.md" Visible="false"/>
        <AdditionalFiles Include="AnalyzerReleases.Unshipped.md" Visible="false"/>
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Properties\" />
    </ItemGroup>
</Project>
