namespace Truffleware.Abstractions.Messaging;

/// <summary>
/// One-to-one messaging construct for handling an incoming request from <see cref="IRequestSender{TRequest,TResponse}"/>.
///
/// Usage auto-generated by <see cref="RequestHandlerAttribute{TRequest,TResponse}"/>.
/// </summary>
/// <typeparam name="TRequest">Incoming type sent to this handler.</typeparam>
/// <typeparam name="TResponse">Outgoing response from this handler back to the sender.</typeparam>
public interface IRequestHandler<in TRequest, TResponse>
{
    Task<TResponse> HandleAsync(TRequest request);
}
